from openai import OpenAI
from dotenv import load_dotenv
import os


load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def llm_agent(features, prediction):
    sys_prompt = """
    ROLE:
    You are a music analysis agent and your task is to provide an insights based on a songs features.
    \n
    INPUTS:
        1) Features: used by the ML model to make prediction. The features are:
            - duration_ms
            - explicit
            - danceability
            - energy
            - key
            - loudness
            - mode
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - time_signature
            - popularity
        2) Popularity: output of the ML model based on the features. It ranges from 1 to 100 where higher values mean higher popularity.
    \n
    EXPECTATION:
    My expectation from you is that you will analyze the values of the features and provide a SLIGHTLY supporting argument for the prediction of the model i.e. the popularity.
    \n
    RULES:
    1) DO NOT mention the feature names (the key) or their values in your output. They are CONFIDENTIAL. Present a general idea.
    2) You NEED to present a concise and general output preferably in two or three sentences.
    3) You HAVE to act like the output was generated by yourself.
    """
    
    user_prompt = f"""
    features: {features}
    predicted popularity: {prediction}
    """
    
    completion = client.chat.completions.create(
      model="gpt-3.5-turbo",
      messages=[
        {"role": "system", "content": sys_prompt},
        {"role": "user", "content": user_prompt}
      ],
      temperature=0.1,
    )
    
    outcome = completion.choices[0].message.content
    
    return outcome